name: Daily Username Checker

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 2 PM UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-script-v2:  # changed from run-script
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python main.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
