name: Daily Username Checker6

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 1 * * *'  

jobs:
  run-script-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: pip install aiohttp requests


      - name: Run script
        run: python Speed.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
